import { NextResponse } from 'next/server';
import { adminAuth, adminDb } from '@/lib/firebase-admin';
import { ROLES, DEFAULT_PERMISSIONS } from '@/lib/auth-utils';
import { cookies } from 'next/headers';

/**
 * Create User API Route (/api/auth/users/create)
 * 
 * WHY: The Firebase Client SDK does not allow creating a user without instantly 
 * signing in as that new user. If an Admin creates a writer, they would be logged out.
 * 
 * HOW: We use the Firebase Admin SDK on the backend. This allows us to securely create
 * accounts on behalf of other users without affecting the Admin's current session.
 */
export async function POST(request) {
  try {
    // 1. Independent Security Check: Do not trust the frontend!
    // Extract the strict httpOnly cookie directly from the Next.js request headers.
    const cookieStore = await cookies();
    const sessionCookie = cookieStore.get('session')?.value;

    if (!sessionCookie) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    // 2. Decrypt the session token to find out WHO is making this request.
    const decodedClaims = await adminAuth.verifySessionCookie(sessionCookie, true);
    const uid = decodedClaims.uid; // The requester's Firebase ID

    // 3. Verify Requester's Role in Firestore
    // We fetch their profile using Admin SDK (which bypasses security rules)
    const adminDoc = await adminDb.collection('users').doc(uid).get();
    
    // CRITICAL: Ensure the requester actually exists, is explicitly an ADMIN, and is ACTIVE.
    if (!adminDoc.exists || adminDoc.data().role !== ROLES.ADMIN || !adminDoc.data().active) {
      return NextResponse.json({ error: 'Forbidden: You are not an active Admin.' }, { status: 403 });
    }

    // 4. Extract new user payload from the request body
    const { email, password, role } = await request.json();

    if (!email || !password || !role) {
      return NextResponse.json({ error: 'Missing required fields' }, { status: 400 });
    }

    // 5. Create the core credential in Firebase Authentication
    // Admin SDK allows us to set the exact password.
    const userRecord = await adminAuth.createUser({
      email,
      password,
      emailVerified: true, // Auto-verify since an admin created them
    });

    // 6. Create the business logic document in Firestore
    // This dictates what the new user can actually do in the CMS.
    const newUserDoc = {
      email,
      role,
      active: true, // Default to active
      permissions: DEFAULT_PERMISSIONS[role] || DEFAULT_PERMISSIONS[ROLES.WRITER],
      createdAt: new Date().toISOString(),
    };

    // Save it to the `/users` collection using the exact UID generated by Firebase Auth.
    await adminDb.collection('users').doc(userRecord.uid).set(newUserDoc);

    // 7. Return the combined data to the frontend so the UI table can update instantly
    // without needing a full page refresh.
    return NextResponse.json({ success: true, user: { id: userRecord.uid, ...newUserDoc } }, { status: 201 });
  } catch (error) {
    console.error('Error creating user:', error);
    if (error.code === 'auth/email-already-exists') {
      return NextResponse.json({ error: 'User with this email already exists.' }, { status: 400 });
    }
    return NextResponse.json({ error: error.message || 'Internal server error' }, { status: 500 });
  }
}
